### PR TITLE
add FBXParser2

### PR DESCRIPTION
**Pull request by kevinypcao**
rewrite fbxparser.

### CODE REVIEW

**Comment by LiXizhi** [comment]
please fix the CI above

https://travis-ci.org/LiXizhi/NPLRuntime/builds/486792430?utm_source=github_status&utm_medium=notification

**Comment by kevinypcao** [comment]
strangely, i can compile success used visual studio 2017.

**Comment by LiXizhi** [comment]
please click to see why it failed on CI.
It must pass all win32 and linux CI build on github before I can merge.

**Comment by kevinypcao** [comment]
ok, i will fixed later.

**Pull request closed without merging**
