### PR TITLE
add wal replication

### PR DESCRIPTION
**Pull request by liuluheng**
This PR mainly add wal page hook and wal check point hook in sqlite. WAL inject page is the crutial point, It cares about the sqlite's internal lock and wal lock, wal header, wal checkpoint etc. It works perfect with the origin sqlite code. When use WAL inject page for replication, It works entirely like a normal wal sqlite. :)

### CODE REVIEW

**Comment by liuluheng** [comment]
this PR can be tested with test_TableDataBase.lua in the TableDB's wal branch

**Comment by LiXizhi** [comment]
Good. I will merge.  Is the current WAL modification to sqlite3 source, enough for all our future RAFT LOG dev?

**Comment by liuluheng** [comment]
Should be enough, When integrated with RAFT, I think the main thing to be cared about is the raft log index and snapshot, mainly the snapshot and checkpoint integration (log index). 

- Raft log index can be correspond to the frame index in sqlite wal. When a checkpoint occurs, the frame index becomes zero (or one). This is _not_ consistent with Raft, in Raft logindex never decrease( and actordb has no checkpoint, so it has no such problem). 

- Snapshot in NPL raft is occured when the log index gap (`currentLogIndex - lastSnapshotIndex`) reaches a certain distance(`RaftParameter.snapshotDistance`). We can make the snapshot adapt to the checkpoint.

- To boost the throughput, I also want to add a `Progress` state to follower in stage 2, like `etcd/raft` [impl](https://github.com/coreos/etcd/blob/master/raft/progress.go#L35)  which may decrease the messages between leader and follower.

- Other miscellaneous like make the server state (`cluster.json`, `server.state`) into a sqlite table in stage 2.

**Comment by LiXizhi** [comment]
OK, can you quickly fix some warnings here before I release it?

```
2>sqlite3.c
2>..\..\..\..\Server\trunk\sqlite-3.6.23.1\sqlite3.c(108747): warning C4028: formal parameter 2 different from declaration
2>..\..\..\..\Server\trunk\sqlite-3.6.23.1\sqlite3.c(139105): warning C4033: 'sqlite3_wal_inject_page' must return a value
2>..\..\..\..\Server\trunk\sqlite-3.6.23.1\sqlite3.c(139118): warning C4090: 'function' : different 'const' qualifiers
2>d:\lxzsrc\paraengine\server\trunk\sqlite-3.6.23.1\wal.c(3440): warning C4700: uninitialized local variable 'pData' used
2>d:\lxzsrc\paraengine\server\trunk\sqlite-3.6.23.1\sqlite3.c(139133): warning C4715: 'sqlite3_wal_inject_page' : not all control paths return a value
```

@liuluheng

**Comment by liuluheng** [comment]
ok

**Pull request merged**
